// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"go-framework/example/internal/server/http"
	"go-framework/example/internal/service"
)

// Injectors from wire.go:

//go:generate wire gen
func InitApp() (*App, func(), error) {
	serviceService, cleanup, err := service.New()
	if err != nil {
		return nil, nil, err
	}
	engine, err := http.New(serviceService)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	app, cleanup2, err := NewApp(serviceService, engine)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
